### ISSUE TITLE
windows version

### ISSUE THREAD

**Issue by jyy1082** [KlabautermannSW/glucotux#1]
Can this project be running on Windows 7? If yes, how should I to do it? Thank you!

**Comment by KlabautermannSW** [comment]
I think you can use most parts directly on Windows 7.
The only thing I do not know is how to get the connection to the device using USB. That is the part done in contour.c.
Everything else is pure C code not depending to an operating system.

Beware in mind that this is a **Linux** project and it's done for **Linux only**. So for the grafic user interface I will use GTK+. From then on the portability will be very small!

**Comment by jyy1082** [comment]
Got it! I will try it on Linux.
Another question, will the program continually run if I remove the device and re-plug it? Do I need to run the program again?

**Comment by KlabautermannSW** [comment]
No idea yet - have to do more tests and research . . .
